version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
