repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.8"
    hooks:
      - id: ruff
        args: ["--no-fix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.7"
    hooks:
      - id: prettier
        exclude: "templates"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.17.1
    hooks:
      - id: slotscheck
        exclude: "test_*|docs|migrations|scripts"
        entry: env PYTHONPATH=src slotscheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1"
    hooks:
      - id: mypy
        exclude: "tools/"
        additional_dependencies:
          [
            pydantic,
            pydantic-settings,
            uvloop,
            passlib,
            packaging,
            asyncpg,
            "litestar[redis,cli,structlog,standard,sqlalchemy]",
            litestar-vite,
            litestar-saq,
            litestar-aiosql,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            types-PyYAML,
            asyncpg-stubs,
          ]
